name: On Release

on:
  release:
    types:
      - released

run-name: Release ${{ github.event.release.tag_name }} by @${{ github.actor }}

jobs:
  publish:
    name: Publish Package
    uses: ./.github/workflows/callable-publish.yml
    permissions:
      id-token: write
      contents: read
